@startuml PackageDiagram

package ui {
    Object ui{
        Handle user input
        Display information to user
    }
}
package persistence{
    object persistence{
        Save to- and load file
        Serialize and deserialize to and from json
    }
}

package core {
    object core{
        Data types
    }
}

package workoutApi {
    object workoutApi{
        Define and implement API
    }
}

ui --> persistence : local
ui --> workoutApi : remote
workoutApi --> persistence
ui --> core
workoutApi --> core
persistence --> core

@enduml